"""create_users_table

Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('talents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_name', sa.String(), nullable=False, unique=True),
    sa.Column('talent_desc', sa.String(), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE talents SET SCHEMA {SCHEMA};")

    op.create_table('character_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer, nullable=False),
    sa.Column('stat_sheet_id', sa.Integer, nullable=False),
    sa.Column('xp_max', sa.Integer, nullable=False, default=500),
    sa.Column('xp_spent', sa.Integer, nullable=False, default=0),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_sheet_id')
    )

    if environment == 'production':
        op.execute(f"ALTER TABLE character_sheets SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_sheets')
    op.drop_column('talents')
    op.drop_table('users')
    # ### end Alembic commands ###
